# https://www.playframework.com/documentation/latest/Configuration

play.filters.enabled += "play.filters.cors.CORSFilter"

slick.dbs.default {
  profile = "slick.jdbc.PostgresProfile$"
  db {
    driver   = "org.postgresql.Driver"
    url      = "jdbc:postgresql://localhost:5432/"${?POSTGRES_DB}
    user     = ${?POSTGRES_USER}
    password = ${?POSTGRES_PASSWORD}
  }
}

play.evolutions.db.default.autoApply = true

play.http.secret.key = ${?APPLICATION_SECRET}

play.filters.cors {
  allowedOrigins = ["http://localhost:5173", "http://127.0.0.1:5173"]
  allowedHttpMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowedHttpHeaders = ["Content-Type", "Authorization"]
}
